Repository devopsdays/devopsdays-web, pull requests merged in 2018-08, with the labels that each got.

#5076 [CAI-2018] move infoglobe logo to correct location
  static/img/sponsors/infoglobe.png
Labels: sponsors

#5134 [BOS-2018] add paul and change conjur logo
  data/events/2018-boston.yml
  data/sponsors/cyberarkconjur2.yml
  static/events/2018-boston/organizers/paulsbruce.jpg
  static/img/sponsors/cyberarkconjur2.png
Labels: do-not-merge

#5144 [DFW-2018] Minor speaker changes
  content/events/2018-dallas/program/karith-foster.md
  content/events/2018-dallas/speakers/karith-foster.md
Labels: do-not-merge

#5224 [Cape Town 2018] Add the program for Cape Town 2018
  content/events/2018-cape-town/program.md
  content/events/2018-cape-town/welcome.md
  data/events/2018-cape-town.yml
Labels: in progress

#5230 [CAI-2018] Updating sponsors data
  data/events/2018-cairo.yml
  data/sponsors/wuzzuf.yml
  static/img/sponsors/BBI.png
  static/img/sponsors/tafra.png
  static/img/sponsors/wuzzuf.png
  tafra.png
Labels: do-not-merge
