Repository devopsdays/devopsdays-web, pull requests merged in 2019-09, with the labels that each got.

#8115 [Cape Town-2019] update Daniel Maher's talk description
  content/events/2019-cape-town/program/daniel-maher.md
Labels: ready

#8216 [ZRH-2020] Add new Event DevOpsDays Zürich 2020
  content/events/2020-zurich/conduct.md
  content/events/2020-zurich/contact.md
  content/events/2020-zurich/location.md
  content/events/2020-zurich/propose.md
  content/events/2020-zurich/registration.md
  content/events/2020-zurich/sponsor.md
  content/events/2020-zurich/welcome.md
  data/events/2020-zurich.yml
Labels: do-not-merge

#8260 [REC-2019] Add initial version
  content/events/2019-recife/conduct.md
  content/events/2019-recife/contact.md
  content/events/2019-recife/local.md
  content/events/2019-recife/welcome.md
  data/events/2019-recife.yml
Labels: do-not-merge

#8313 [Columbus-2019] Adding images for two speakers.
  content/events/2019-columbus/speakers/ed-legault.md
  content/events/2019-columbus/speakers/kristen-biddulph.md
  static/events/2019-columbus/speakers/ed-legault.jpg
  static/events/2019-columbus/speakers/kristen-biddulph.jpeg
Labels: do-not-merge

#8405 [AMS2020] Let's get this party started
  content/events/2020-amsterdam/conduct.md
  content/events/2020-amsterdam/contact.md
  content/events/2020-amsterdam/location.md
  content/events/2020-amsterdam/propose.md
  content/events/2020-amsterdam/registration.md
  content/events/2020-amsterdam/sponsor.md
  content/events/2020-amsterdam/welcome.md
  data/events/2020-amsterdam.yml
Labels: do-not-merge

#8407 [STH-2019] add slides
  content/events/2019-stockholm/program/abdelfettah-sghiouar.md
  content/events/2019-stockholm/program/daniel-maher-2.md
  content/events/2019-stockholm/program/daniel-maher.md
  content/events/2019-stockholm/program/felisia-martini-derik-evangelista.md
  content/events/2019-stockholm/program/heidi-araya.md
  content/events/2019-stockholm/program/jj-asghar.md
  content/events/2019-stockholm/program/ken-mugrage.md
  content/events/2019-stockholm/program/krikor-maroukian.md
  content/events/2019-stockholm/program/kris-buytaert.md
  content/events/2019-stockholm/program/marcus-olsson.md
  content/events/2019-stockholm/program/mark-baker.md
  content/events/2019-stockholm/program/mikael-sundberg.md
  content/events/2019-stockholm/program/philipp-krenn.md
  content/events/2019-stockholm/program/pia-fåk-sunnanbo.md
  content/events/2019-stockholm/program/waldo-g.md
  content/events/2019-stockholm/speakers/kris-buytaert.md
  data/events/2019-stockholm.yml
  static/events/2019-stockholm/speakers/kris-buytaert.jpg
Labels: do-not-merge

#8431 Organizer refactor
  content/page/about.md
  data/core.toml
  themes/devopsdays-theme/layouts/shortcodes/list_core.html
  themes/devopsdays-theme/layouts/shortcodes/list_core_active.html
  themes/devopsdays-theme/layouts/shortcodes/list_core_advisory.html
  themes/devopsdays-theme/layouts/shortcodes/list_core_emeritus.html
  utilities/examples/content/events/yyyy-city/contact.md
Labels: do-not-merge, in progress
